apiVersion: v1
kind: Service
metadata:
  name: practica2
  labels:
    app: practica2
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
    port: 80
  selector:
    app: practica2
